// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Data.DbContexts;

namespace StarWars.Data.Migrations
{
    [DbContext(typeof(StarWarsDbContext))]
    [Migration("20200212180016_PlanetIntroduction")]
    partial class PlanetIntroduction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWars.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Episodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarWars.Domain.Entities.CharacterFriendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FirstId");

                    b.HasIndex("SecondId");

                    b.ToTable("CharacterFriendships");
                });

            modelBuilder.Entity("StarWars.Domain.Entities.CharacterFriendship", b =>
                {
                    b.HasOne("StarWars.Domain.Entities.Character", null)
                        .WithMany("Friendships")
                        .HasForeignKey("CharacterId");

                    b.HasOne("StarWars.Domain.Entities.Character", "First")
                        .WithMany("FriendshipsWhereIsFirst")
                        .HasForeignKey("FirstId");

                    b.HasOne("StarWars.Domain.Entities.Character", "Second")
                        .WithMany("FriendshipsWhereIsSecond")
                        .HasForeignKey("SecondId");
                });
#pragma warning restore 612, 618
        }
    }
}
